In [7]:
import numpy as np

array1 = np.array([1,2,3])
print(array1.shape)
print(array1)

print(array1[0], array1[2])
array1[1] = 10
print(array1)

array2 = np.array([[1,2,3],[4,5,6]])
print(array2.shape)
print(array2)
print(array2[0,0], array2[0,2], array2[1,0])

(3,)
[1 2 3]
1 3
[ 1 10  3]
(2, 3)
[[1 2 3]
 [4 5 6]]
1 3 4


In [12]:
import numpy as np

a = np.zeros((2,3))
print(a)

b = np.ones((1,2))
print(b)

c = np.random.random((2,2))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[0.87293455 0.0772142 ]
 [0.0050757  0.86486997]]


In [16]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

b = a[:2, 1:3]
print(b)

a1 = a[1, :]
a2 = a[:2, :]
print(a1)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
x = np.array([1,2])
print(x.dtype)
print(x)

x = np.array([1.0, 2.0])
print(x.dtype)
print(x)

x = np.array([1,2], dtype=np.float64)
print(x.dtype)
print(x)

int64
[1 2]
float64
[1. 2.]
float64
[1. 2.]


In [23]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

print(x + y)
print(np.add(x, y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x)
print(y)
print(v)
print(w)

print(v.dot(w))
print(np.dot(v,w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
